services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: cashback
      POSTGRES_PASSWORD: cashback
      POSTGRES_DB: cashbackapp
    ports:
      - "5433:5432"
    volumes:
      - cashback_postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - cashback_redis_data:/data

volumes:
  cashback_postgres_data:
  cashback_redis_data:
